### ISSUE TITLE
ERROR: libbluray.so.1

### ISSUE THREAD

**Issue by tinitussi** [VDR4Arch/vdr4arch#158]
Hello,

after a update I get this Error:
ERROR: libbluray.so.1 not found
 vdr.service: Unit entered failed state.

pacman -S libbluray
Warnung: libbluray-1.0.0-1 ist aktuell -- Reinstalliere
Löse Abhängigkeiten auf...
Suche nach in Konflikt stehenden Paketen...

**Comment by M-Reimer** [comment]
Please provide full list of enabled plugins.

**Comment by tinitussi** [comment]
With the xineliboutput Update all works fine.... Thanks

**Comment by M-Reimer** [comment]
After updating my system today, I got the same issue. It is in fact some incompatibility between libbluray and xineliboutput. I've fixed this by pushing xineliboutput to the latest GIT version. So this issue is now officially closed by https://github.com/VDR4Arch/vdr4arch/commit/7131af8001461f290dc20d15f05dd9fc17a5a192 and the binary packages will have the fix with the next build run.
