### ISSUE TITLE
core dump in vdr - epgsearch

### ISSUE THREAD

**Issue by nafets227** [VDR4Arch/vdr4arch#208]
vdr is core-dumping at my machine with latest archlinux updates. EpgSearch seems to be the "guilty" as discbling the Plugin in /etc/vdr/conf.d solves the issue.
Updating to the latest epgsearch from git (commit #770de32) also solves the issue.

> --- a/plugins/vdr-epgsearch/PKGBUILD
> +++ b/plugins/vdr-epgsearch/PKGBUILD
> @@ -2,8 +2,8 @@
> 
>  \# Maintainer: Christopher Reimer <mail+vdr4arch[at]c-reimer[dot]de>
>  pkgname=vdr-epgsearch
> -pkgver=2.4.0.r0.g84b59b8
> -_gitver=84b59b81137887a48533cc897551bccf2e9e10f6
> +pkgver=2.4.0.r0nafets1.g770de32
> +_gitver=770de32f1908b1f9c60f66bf288a4c8a03f97d52
>  _vdrapi=2.4.0
>  epoch=1
>  pkgrel=1`

**Comment by M-Reimer** [comment]
Thanks for reporting.
There is a good chance that other plugins cause similar errors.
I need to be notified about this if someone has problems as I don't test all the plugins regularly.
The problem is, that these "vdr patchwork", Klaus is currently doing, sometimes seems to change API functions that are used by plugins.
To be on the safe side, it would be currently the best thing to rebuild all plugins with every VDR update but I'm too lazy for that and at least so far the few plugins I'm using (only need a few things to get Kodi connected) keep running.
