### ISSUE TITLE
vdr-plugin-robotv

### ISSUE THREAD

**Issue by romrich** [VDR4Arch/vdr4arch#238]
Please add support of vdr-plugin-robotv (see https://github.com/pipelka/vdr-plugin-robotv/).

**Comment by M-Reimer** [comment]
I have no way of testing this. So it would be best if you prepare a PKGBUILD which works for you and then create a pull request to get it merged.

The only other option could be that I prepare an untested PKGBUILD on a new branch for you to test. This would only get included if you verify that this works.

Please tell me which way you would prefer. Otherwise I have to close this one as "won't fix" as I don't want to add new, completely untested, plugins PKGBUILDs.

**Comment by M-Reimer** [comment]
I'm closing here for now. If you are still interested in getting robotv added, then please resubmit using the newly created issue template: https://github.com/VDR4Arch/vdr4arch/issues/new?assignees=&labels=enhancement&template=package-request.yml
