### ISSUE TITLE
rpihddevice MPEG-2 Support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [VDR4Arch/vdr4arch#85]
Hi again,

do you know if the package rpihddevice is really working with MPEG-2 Codecs?

On my Arch installation I've got ffmpeg and all the codecs needed to decode this (libmpeg2 installed). But If I try to see a channel what I get is:

```bash
# journalctl -xe
vdr[255]: [284] rpihddevice: [libav] incomplete frame
vdr[255]: [284] rpihddevice: [libav] Codec type or id mismatches
```

what am I doing wrong? The audio meanwhile is working. I'm using `xineliboutput` through `vdr-fbfe` with `--video=fb`.

Thanks in advice :)

**Comment by julianxhokaxhiu** [comment]
Found it!

There was no documentation about this but I had to add these two flags to make it work in `/etc/vdr/conf.d/50-xineliboutput.conf`

```bash
[xineliboutput]
--hud=opengl
--opengl
```

I'll leave this for documentation for someone else having my problem :)

**Comment by CReimer** [comment]
But you know that you're using two different output plugins?
You can only use one output plugin at a time. Either rpihddevice or xineliboutput. Never both of them.

**Comment by julianxhokaxhiu** [comment]
Oh, so I don't need xineliboutput to see the FE on VDR?

**Comment by CReimer** [comment]
Of course not. Splitting frontend and backend is obsolete. And IMO xineliboutput is obsolete, too.

As input plugin you either use satip or streamdev and as output plugin rpihddevice.
As far as I know xineliboutput or rather xinelib is unable to play hardware accelerated video on the RPi
You may want to use some additional plugins like remotetimers to set timers on a vdr server instead of your RPi

I think I should drop xineliboutput out of vdr4arch. It's still more or less actively developed, but I don't see any good reason to keep it.
For VDPAU and VAAPI we have softhddevice and for RPi rpihddevice

**Comment by julianxhokaxhiu** [comment]
Good, for me everything is ok, I like clean stuff and I think that rpihddevice is the way to go.

Only one question: how can I set the Audio Output to HDMI for rpihddevice?

**Comment by CReimer** [comment]
As far as I remember there's an OSD setting for this.

**Comment by julianxhokaxhiu** [comment]
Yep found there, I meant the .conf settings but I found them also after I did that on the OSD :) Thanks for all the support. Everything now works out-of-the-box :D
